# @package _global_

defaults:
  - _self_
  - datamodule: trackml.yaml # choose datamodule with `test_dataloader()` for evaluation
  - model: trackml.yaml
  - logger: tensorboard
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: /home/alinal/projects/scaleTrackML/logs/train/runs/2022-10-30_17-46-11/checkpoints/epoch_048.ckpt
