_target_: src.datamodules.trackml_datamodule.TRACKMLDataModule
data_dir: /fs/scratch/PLS0144/alina/embedding_processed/1GeV_pt_cut #${paths.data_dir}
#data_dir: /users/PLS0129/ysu0053/exatrkx-inference/notebooks/data/small
#data_dir: /fs/ess/PLS0144/alina/0_pt_cut_endcaps_connected_high_eff
datatype_names: [train, val, test, test]
datatype_split: [80, 10, 10, 10]
num_workers: 40
pin_memory: True
#loader: 
#  _target_: torch_geometric.loader.DataLoader
batch_size: 1
loader: "neighbor"
neighb: 5
